import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: "#FFFFFF",
  },
  headerLeftContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  avatarHeaderWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarHeader: {
    width: "100%",
    height: "100%",
    borderRadius: 22,
  },
  headerTitleContainer: {
    flex: 1,
    gap: 1,
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginTop: 1,
  },
  locationText: {
    fontSize: 13,
    fontWeight: "700",
  },
  nearbySummaryText: {
    fontSize: 11,
    fontWeight: "500",
    marginTop: 2,
  },
  greeting: { fontSize: 18, fontWeight: "800", color: "#111827" },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 8 },
  editModeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  editModeBtnActive: {
    backgroundColor: "#25D366",
    borderColor: "#25D366",
  },
  editModeBtnLabel: { fontSize: 12, fontWeight: "700", color: "#FFFFFF" },
  bellBtn: { padding: 4 },
  locationWarningBanner: {
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
  },
  locationWarningHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  locationWarningTitle: {
    fontSize: 15,
    fontWeight: "700",
  },
  locationWarningText: {
    fontSize: 13,
    lineHeight: 18,
  },
  locationWarningBtn: {
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  locationWarningBtnText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  bellWrapper: { position: "relative" },
  badge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#EF4444",
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  badgeText: { color: "#FFFFFF", fontSize: 9, fontWeight: "700" },
  editBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#25D366",
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  editBannerText: {
    flex: 1,
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    gap: 12,
    marginTop: 8,
    marginBottom: 4,
  },
  searchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "ios" ? 12 : 8,
    gap: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  filterBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 12,
    height: Platform.OS === "ios" ? 48 : 42,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    position: "relative",
  },
  filterBtnText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#25D366",
  },
  filterActiveDot: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#25D366",
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  filterSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
  },
  filterOptions: {
    marginTop: 20,
    gap: 10,
  },
  filterOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  filterOptionSelected: {
    backgroundColor: "#F0FDF4",
    borderColor: "#25D366",
  },
  filterOptionText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "500",
    color: "#4B5563",
  },
  filterOptionTextSelected: {
    color: "#15803D",
    fontWeight: "700",
  },
  applyFilterBtn: {
    marginTop: 24,
    backgroundColor: "#25D366",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  applyFilterBtnText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  searchTextInput: {
    flex: 1,
    fontSize: 14,
    color: "#111827",
    padding: 0,
  },
  searchPlaceholder: { fontSize: 14, color: "#9CA3AF" },
  categoriesContainer: { paddingHorizontal: 16, paddingVertical: 16, gap: 12 },
  categoryItem: { alignItems: "center", width: 76, gap: 6 },
  categoryIconBox: {
    width: 60,
    height: 60,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  categoryLabel: {
    fontSize: 11,
    color: "#374151",
    textAlign: "center",
    fontWeight: "500",
    lineHeight: 14,
  },
  sectionWrapper: { marginTop: 8, paddingHorizontal: 16 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  sectionTitle: { fontSize: 17, fontWeight: "700", color: "#111827" },
  seeAll: { fontSize: 13, color: "#1A73E8", fontWeight: "500" },
  loadingRow: { height: 120, alignItems: "center", justifyContent: "center" },
  emptySearch: {
    height: 100,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
  },
  emptySearchText: {
    fontSize: 14,
    color: "#9CA3AF",
  },
  searchResultContainer: {
    marginTop: 12,
    paddingHorizontal: 20,
  },
  searchResultHeader: {
    marginBottom: 16,
  },
  searchResultTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6B7280",
  },
  verticalResultsList: {
    gap: 12,
  },
  verticalServiceCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  verticalCardContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  verticalCardImage: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
  },
  verticalCardIconBg: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#F0FDF4",
    alignItems: "center",
    justifyContent: "center",
  },
  verticalCardInfo: {
    flex: 1,
    gap: 2,
  },
  verticalCardName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  verticalCardCategory: {
    fontSize: 13,
    color: "#25D366",
    fontWeight: "600",
  },
  verticalCardDesc: {
    fontSize: 13,
    color: "#6B7280",
  },
  emptySearchLarge: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    gap: 12,
  },
  emptySearchTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#374151",
    marginTop: 8,
  },
  emptySearchSub: {
    fontSize: 14,
    color: "#9CA3AF",
    textAlign: "center",
  },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#25D366",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  addBtnText: { fontSize: 12, fontWeight: "700", color: "#FFFFFF" },
  adminServicesRow: { gap: 12, paddingBottom: 8 },
  adminServiceCard: {
    width: 130,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  adminServiceCardEdit: {
    borderColor: "#25D366",
    borderWidth: 2,
    shadowColor: "#25D366",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  adminServiceCardDragging: {
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    transform: [{ scale: 1.05 }],
  },
  adminServiceImage: { width: "100%", height: 90, backgroundColor: "#F3F4F6" },
  adminServiceIconBg: {
    width: "100%",
    height: 90,
    backgroundColor: "#F0FDF4",
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#BBF7D0",
  },
  adminServiceInfo: { padding: 8, gap: 2 },
  adminServiceName: { fontSize: 12, fontWeight: "700", color: "#111827" },
  adminServiceCategory: { fontSize: 11, color: "#6B7280" },
  whatsappMiniBtn: {
    position: "absolute",
    bottom: 36,
    right: 6,
    backgroundColor: "#25D366",
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  editOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.45)",
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  dragHandle: { padding: 4 },
  editActions: { flexDirection: "row", gap: 4 },
  editBtn: {
    backgroundColor: "#3B82F6",
    borderRadius: 8,
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteBtn: {
    backgroundColor: "#EF4444",
    borderRadius: 8,
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyAddCard: {
    height: 100,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "#25D366",
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#F0FDF4",
    marginBottom: 8,
  },
  emptyAddText: { fontSize: 13, color: "#15803D", fontWeight: "500" },
  cardsRow: { flexDirection: "row", gap: 10, marginBottom: 8 },
  serviceCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  serviceImage: { width: "100%", height: 90, backgroundColor: "#F3F4F6" },
  serviceName: {
    fontSize: 12,
    fontWeight: "500",
    color: "#111827",
    padding: 8,
    paddingTop: 6,
    lineHeight: 16,
  },
  premiumHeaderRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  modalOverlay: { flex: 1, justifyContent: "flex-end" },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  modalSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
    maxHeight: "90%",
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#E5E7EB",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 4,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 6,
    marginTop: 14,
  },
  fieldHint: { fontSize: 11, color: "#9CA3AF", marginTop: 4, lineHeight: 16 },
  textInput: {
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#111827",
    backgroundColor: "#FAFAFA",
  },
  dropdownTrigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#FAFAFA",
  },
  dropdownTriggerText: { fontSize: 14, color: "#111827", flex: 1 },
  dropdownList: {
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    marginTop: 4,
    overflow: "hidden",
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  dropdownItemSelected: { backgroundColor: "#F0FDF4" },
  dropdownItemText: { flex: 1, fontSize: 14, color: "#374151" },
  dropdownItemTextSelected: { color: "#15803D", fontWeight: "600" },
  imagePicker: {
    height: 120,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    overflow: "hidden",
    backgroundColor: "#FAFAFA",
  },
  imagePreview: { width: "100%", height: "100%" },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  imageOverlayText: { color: "#FFFFFF", fontSize: 13, fontWeight: "600" },
  imagePlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  imagePlaceholderText: { fontSize: 13, color: "#9CA3AF" },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 16,
    paddingVertical: 4,
  },
  toggleLabel: { fontSize: 14, fontWeight: "600", color: "#111827" },
  toggleSub: { fontSize: 12, color: "#9CA3AF", marginTop: 2 },
  toggleSwitch: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#E5E7EB",
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  toggleSwitchOn: { backgroundColor: "#25D366" },
  toggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  toggleThumbOn: { alignSelf: "flex-end" },
  modalActions: { flexDirection: "row", gap: 12, marginTop: 24 },
  cancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    alignItems: "center",
  },
  cancelBtnText: { fontSize: 15, fontWeight: "600", color: "#374151" },
  saveBtn: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#25D366",
    alignItems: "center",
  },
  saveBtnText: { fontSize: 15, fontWeight: "700", color: "#FFFFFF" },
  categoryBlock: { marginBottom: 24 },
  categoryHeaderVertical: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  categoryTitleVertical: { fontSize: 16, fontWeight: "700", color: "#111827" },
  categorySubtitleVertical: { fontSize: 12, color: "#6B7280", marginTop: 2 },
  seeAllText: { fontSize: 13, fontWeight: "600", color: "#25D366" },
  subCatList: { paddingHorizontal: 16, gap: 12 },
  subCatCard: {
    width: 140,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    borderRadius: 16,
    overflow: "hidden",
  },
  subCatImageWrapper: {
    width: "100%",
    height: 90,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  subCatImage: { width: "100%", height: "100%" },
  subCatPlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  subCatInfo: { padding: 10, height: 50, justifyContent: "center" },
  subCatName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111827",
    lineHeight: 18,
  },
  emptySubCat: { paddingHorizontal: 16, paddingBottom: 8 },
  emptySubCatText: { fontSize: 13, color: "#9CA3AF" },
  horizontalCatsWrapper: {
    marginBottom: 20,
  },
  horizontalCatsContent: {
    paddingHorizontal: 16,
    gap: 16,
  },
  quickCatBtn: {
    alignItems: "center",
    width: 80,
  },
  quickCatIconBg: {
    width: 64,
    height: 64,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  quickCatLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#4B5563",
    textAlign: "center",
    lineHeight: 14,
  },
  horizontalProvidersContent: {
    paddingHorizontal: 16,
    gap: 12,
    paddingBottom: 8,
  },
  horizontalProfCard: {
    width: 130,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#F3F4F6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },
  profCardAvatarWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 10,
    position: "relative",
  },
  profCardAvatar: { width: "100%", height: "100%", borderRadius: 40 },
  profCardAvatarFallback: {
    width: "100%",
    height: "100%",
    borderRadius: 40,
    backgroundColor: "#F0FDF4",
    alignItems: "center",
    justifyContent: "center",
  },
  profCardRatingBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    backgroundColor: "#25D366",
    borderRadius: 12,
    paddingHorizontal: 6,
    paddingVertical: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  profCardRatingText: { fontSize: 10, fontWeight: "800", color: "#FFFFFF" },
  profCardName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 2,
    textAlign: "center",
  },
  profCardCategory: { fontSize: 11, color: "#9CA3AF", textAlign: "center" },
  suggestionsContainer: {
    backgroundColor: "#F0FDF4",
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#DCFCE7",
  },
  suggestionsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 4,
  },
  suggestionsTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#065F46",
  },
  suggestionsSubtitle: {
    fontSize: 12,
    color: "#4B5563",
    marginBottom: 16,
    fontWeight: "500",
    textAlign: "center",
  },
  suggestionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 2,
    elevation: 1,
  },
  suggestionImage: {
    width: 48,
    height: 48,
    borderRadius: 12,
    marginRight: 12,
    backgroundColor: "#E5E7EB",
  },
  suggestionInfo: {
    flex: 1,
    justifyContent: "center",
  },
  suggestionName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 4,
  },
  suggestionMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  suggestionMetaText: {
    fontSize: 11,
    color: "#6B7280",
    fontWeight: "500",
  },
  moreSuggestionsBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#22C55E",
    borderRadius: 12,
    paddingVertical: 12,
    marginBottom: 20,
    gap: 6,
  },
  moreSuggestionsText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#22C55E",
  },
  feedbackContainer: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#BBF7D0",
    borderRadius: 18,
    padding: 16,
    backgroundColor: "transparent",
  },
  feedbackHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  feedbackIconBg: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#1F2937",
    alignItems: "center",
    justifyContent: "center",
  },
  feedbackHeaderText: {
    flex: 1,
  },
  feedbackTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 2,
  },
  feedbackSubtitle: {
    fontSize: 11,
    color: "#4B5563",
  },
  feedbackForm: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  feedbackInput: {
    flex: 1,
    height: 40,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 13,
    color: "#1F2937",
  },
  feedbackSubmitBtn: {
    backgroundColor: "#059669",
    height: 40,
    borderRadius: 10,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  feedbackSubmitText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  featuredCard: {
    width: 250,
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },
  featuredImageWrapper: {
    width: "100%",
    height: 110,
    position: "relative",
    backgroundColor: "#F3F4F6",
  },
  featuredImage: {
    width: "100%",
    height: "100%",
  },
  sponsoredBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  sponsoredText: {
    color: "#FFFFFF",
    fontSize: 8,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  featuredInfo: {
    padding: 10,
    gap: 4,
  },
  featuredTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  featuredName: {
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
  featuredSub: {
    fontSize: 11,
    color: "#6B7280",
  },
  featuredBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  ratingText: {
    fontSize: 11,
    fontWeight: "600",
  },
  abertoBadge: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  abertoText: {
    color: "#15803D",
    fontSize: 9,
    fontWeight: "800",
  },
  popularPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  popularIconBg: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  popularName: {
    fontSize: 12,
    fontWeight: "700",
  },
  popularCount: {
    fontSize: 10,
    color: "#9CA3AF",
    marginTop: 1,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
});
